(async () => {
  const data = window.OVERLAY_DATA || { categories: [] };
  document.title = data.title || 'Tela de Apoiadores';
  const canvas = document.createElement('canvas'); const context = canvas.getContext('2d'); document.body.append(canvas);
  const veil = document.createElement('div'); veil.className = 'veil'; document.body.append(veil);
  const content = document.createElement('main'); content.className = 'content'; content.style.fontFamily = data.fontFamily || 'Impact, Arial Black, sans-serif';
  const title = document.createElement('h1'); const names = document.createElement('div'); names.className = 'names'; content.append(title, names); document.body.append(content);
  const categories = data.categories || []; let screen = 0, pages = [];
  function titleFor(category) { return `${data.title || 'Agradecimentos especiais aos nossos apoiadores'} ${category.name}`; }
  function buildPages() { pages = []; const contentStyle = getComputedStyle(content), namesStyle = getComputedStyle(names); const padding = parseFloat(contentStyle.paddingTop) + parseFloat(contentStyle.paddingBottom); const lineHeight = parseFloat(namesStyle.lineHeight) || parseFloat(namesStyle.fontSize) * 1.26; const columns = Number.parseInt(namesStyle.columnCount, 10) || 3;
    categories.forEach(category => { title.textContent = titleFor(category); const titleStyle = getComputedStyle(title); const titleSpace = title.getBoundingClientRect().height + parseFloat(titleStyle.marginBottom); const linesPerColumn = Math.max(1, Math.floor((innerHeight - padding - titleSpace) / lineHeight) - 1); const pageSize = Math.max(columns, linesPerColumn * columns); for (let start = 0; start < category.names.length; start += pageSize) pages.push({ category, names: category.names.slice(start, start + pageSize) }); });
  }
  function showScreen() { const page = pages[screen]; if (!page) { title.textContent = 'Nenhum apoiador selecionado'; names.replaceChildren(); return; } title.textContent = titleFor(page.category); names.replaceChildren(); page.names.forEach(name => { const line = document.createElement('div'); line.textContent = name; names.append(line); }); screen = (screen + 1) % pages.length; }
  buildPages(); showScreen(); if (pages.length > 1) setInterval(showScreen, Math.max(1, Number(data.durationSeconds) || 5) * 1000);
  if (data.audioFile) { const audio = new Audio(data.audioFile); audio.loop = true; audio.volume = .72; audio.play().catch(() => { document.body.addEventListener('click', () => audio.play(), { once: true }); }); }
  let width, height, time = 0; const random = seeded(data.background || 'prismas'); const points = Array.from({ length: 48 }, () => ({ x: random(), y: random(), vx: (random()-.5)*.00048, vy: (random()-.5)*.00048, size: random()*2+1 }));
  function resize() { const ratio = devicePixelRatio || 1; width = innerWidth; height = innerHeight; canvas.width = width * ratio; canvas.height = height * ratio; context.setTransform(ratio,0,0,ratio,0,0); buildPages(); screen = 0; showScreen(); }
  addEventListener('resize', resize); resize();
  function draw() { time += .008; context.clearRect(0,0,width,height); const mode = data.background || 'prismas';
    const palettes = { prismas:['#031426','#0d5471','#8560c9'], neon:['#13052d','#ed2495','#21ddff'], matrix:['#021b1b','#07a081','#7fffc3'], aurora:['#07142d','#7752e8','#19d5ca'] }; const color = data.backgroundColors?.length === 3 ? data.backgroundColors : (palettes[mode] || palettes.prismas);
    const gradient = context.createLinearGradient(0,0,width,height); gradient.addColorStop(0,color[0]); gradient.addColorStop(.55,'#061223'); gradient.addColorStop(1,color[1]); context.fillStyle=gradient; context.fillRect(0,0,width,height);
    if (mode === 'aurora') drawAurora(color); else if (mode === 'neon') drawNeon(color); else drawNetwork(color, mode === 'prismas'); requestAnimationFrame(draw);
  }
  function drawNetwork(color, triangles) { const line = hexRgb(color[1]), glow = hexRgb(color[2]); points.forEach(point => { point.x += point.vx; point.y += point.vy; if(point.x<0||point.x>1)point.vx*=-1;if(point.y<0||point.y>1)point.vy*=-1; });
    context.lineWidth=1; for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=points[i],b=points[j],dx=(a.x-b.x)*width,dy=(a.y-b.y)*height,d=Math.hypot(dx,dy);if(d<260){context.strokeStyle=`rgba(${line},${.3*(1-d/260)})`;context.beginPath();context.moveTo(a.x*width,a.y*height);context.lineTo(b.x*width,b.y*height);context.stroke();if(triangles&&j%5===0){context.fillStyle=`rgba(${line},${.07*(1-d/260)})`;context.beginPath();context.moveTo(a.x*width,a.y*height);context.lineTo(b.x*width,b.y*height);context.lineTo(points[(j+7)%points.length].x*width,points[(j+7)%points.length].y*height);context.fill();}}}
    if(triangles){for(let i=0;i<9;i++){const x=(Math.sin(time*.9+i*1.8)*.42+.5)*width,y=(Math.cos(time*.72+i*2.4)*.34+.5)*height,s=70+Math.sin(time+i)*35;context.save();context.translate(x,y);context.rotate(time*.25+i);context.fillStyle=`rgba(${glow},${.1+Math.sin(time+i)*.025})`;context.beginPath();context.moveTo(0,-s);context.lineTo(s*.86,s*.5);context.lineTo(-s*.86,s*.5);context.closePath();context.fill();context.restore();}}points.forEach(point=>{context.fillStyle=color[2];context.globalAlpha=.55;context.beginPath();context.arc(point.x*width,point.y*height,point.size,0,7);context.fill();context.globalAlpha=1;}); }
  function drawNeon(color) { for(let i=0;i<6;i++){const x=(Math.sin(time*(.4+i*.05)+i*2)*.35+.5)*width,y=(Math.cos(time*(.3+i*.06)+i)*.34+.48)*height,r=width*(.1+i*.025);const g=context.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`${color[(i%2)+1]}55`);g.addColorStop(1,'transparent');context.fillStyle=g;context.fillRect(0,0,width,height);} drawNetwork(color,false); }
  function drawAurora(color) { context.globalCompositeOperation='screen'; for(let i=0;i<4;i++){context.beginPath();for(let x=0;x<=width;x+=12){const y=height*(.25+i*.15)+Math.sin(x/width*7+time*(1+i*.2)+i)*height*.09; x?context.lineTo(x,y):context.moveTo(x,y);}context.lineTo(width,height);context.lineTo(0,height);context.closePath();const g=context.createLinearGradient(0,0,0,height);g.addColorStop(0,`${color[(i%2)+1]}00`);g.addColorStop(.45,`${color[(i%2)+1]}36`);g.addColorStop(1,'transparent');context.fillStyle=g;context.fill();}context.globalCompositeOperation='source-over'; }
  draw();
  function hexRgb(hex){const value=hex.replace('#','');return `${parseInt(value.slice(0,2),16)},${parseInt(value.slice(2,4),16)},${parseInt(value.slice(4,6),16)}`;}
  function seeded(input){let seed=0;for(const char of input)seed=(seed*31+char.charCodeAt(0))>>>0;return()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);}
})();
