const state = { headers: [], rows: [], selectedCategories: new Set(), background: 'prismas', audioPath: null, exportedIndex: null };
const preferred = { name: ['Apoiador', 'Nome do apoiador', 'Nome'], category: ['Recompensa', 'Faixa de Recompensa', 'Categoria'], status: ['Status da Promessa', 'Status atual do apoio', 'Status do apoio'] };
const backgrounds = [['prismas', 'Prismas cósmicos'], ['neon', 'Nebulosa neon'], ['matrix', 'Grade quântica'], ['aurora', 'Aurora geek']];
const $ = (id) => document.getElementById(id);

backgrounds.forEach(([key, label]) => { const button = document.createElement('button'); button.className = `background ${key}${key === state.background ? ' selected' : ''}`; button.innerHTML = `<span>${label}</span>`; button.onclick = () => { state.background = key; document.querySelectorAll('.background').forEach(b => b.classList.toggle('selected', b === button)); render(); }; $('backgrounds').append(button); });
$('choose-csv').onclick = async () => { const filePath = await window.desktop.selectFile([{ name: 'CSV', extensions: ['csv'] }]); if (!filePath) return; const parsed = parseCsv(await window.desktop.readTextFile(filePath)); if (!parsed.headers.length) return setStatus('Não foi possível ler o cabeçalho do CSV.'); state.headers = parsed.headers; state.rows = parsed.rows; populateMappings(); $('csv-name').textContent = `${basename(filePath)} · ${parsed.rows.length} registros`; $('mapping-section').hidden = false; $('categories-section').hidden = false; $('export').disabled = false; updateData(); };
$('choose-audio').onclick = async () => { const filePath = await window.desktop.selectFile([{ name: 'Áudio', extensions: ['mp3', 'wav', 'ogg', 'm4a'] }]); if (!filePath) return; state.audioPath = filePath; $('audio-name').textContent = basename(filePath); render(); };
['name-column', 'category-column', 'status-column', 'active-status'].forEach(id => $(id).addEventListener('input', updateData));
['title', 'font-family', 'duration'].forEach(id => $(id).addEventListener('input', render));
$('copy-path').onclick = async () => { if (!state.exportedIndex) return; await window.desktop.copyText(state.exportedIndex); $('copy-path').textContent = 'Endereço copiado'; setTimeout(() => { $('copy-path').textContent = 'Copiar endereço do arquivo'; }, 1800); };
$('export').onclick = async () => { const data = currentData(); if (!data.categories.length) return setStatus('Não há apoiadores ativos nas categorias selecionadas.'); const result = await window.desktop.exportOverlay(exportPayload(data)); if (!result.canceled) { state.exportedIndex = result.indexPath; $('export-result').textContent = `Pronto: ${result.indexPath}`; $('copy-path').hidden = false; setStatus('Ciclo de telas pronto para o OBS'); } };

function populateMappings() { for (const [kind, options] of Object.entries(preferred)) { const select = $(`${kind}-column`); select.replaceChildren(); state.headers.forEach(header => select.add(new Option(header, header))); select.value = options.find(option => state.headers.includes(option)) || state.headers[0]; } }
function updateData() { renderCategories(); render(); }
function currentData() { const name = $('name-column').value, category = $('category-column').value, status = $('status-column').value, allowed = normalise($('active-status').value); const grouped = new Map(); state.rows.filter(row => normalise(row[status]) === allowed && String(row[name] || '').trim() && String(row[category] || '').trim()).forEach(row => { const key = String(row[category]).trim(); if (!grouped.has(key)) grouped.set(key, new Set()); grouped.get(key).add(String(row[name]).trim()); }); return { grouped, categories: [...grouped.entries()].filter(([key]) => state.selectedCategories.has(key)).sort(([a], [b]) => a.localeCompare(b, 'pt-BR')).map(([name, names]) => ({ name, names: [...names].sort((a, b) => a.localeCompare(b, 'pt-BR', { sensitivity: 'base' })) })) }; }
function renderCategories() { const { grouped } = currentData(); if (!state.selectedCategories.size || [...state.selectedCategories].some(key => !grouped.has(key))) state.selectedCategories = new Set(grouped.keys()); $('category-list').replaceChildren(); [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b, 'pt-BR')).forEach(([name, names]) => { const line = document.createElement('label'); line.className = 'category-item'; const check = document.createElement('input'); check.type = 'checkbox'; check.checked = state.selectedCategories.has(name); check.onchange = () => { check.checked ? state.selectedCategories.add(name) : state.selectedCategories.delete(name); render(); }; line.append(check, document.createTextNode(name), Object.assign(document.createElement('span'), { textContent: names.size })); $('category-list').append(line); }); }
function exportPayload(data) { return { title: $('title').value.trim(), background: state.background, fontFamily: $('font-family').value, durationSeconds: clampNumber($('duration').value, 5), categories: data.categories, audioPath: state.audioPath }; }
function render() { const data = currentData(), total = data.categories.reduce((sum, item) => sum + item.names.length, 0), payload = exportPayload(data); $('active-count').textContent = total; $('category-count').textContent = data.categories.length; $('sample-list').innerHTML = data.categories.length ? data.categories.map((item, index) => `<div class="sample-category"><strong>Tela ${index + 1}: ${escapeHtml(item.name)} (${item.names.length})</strong><p>${escapeHtml(payload.title)} ${escapeHtml(item.name)}<br>${item.names.slice(0, 5).map(escapeHtml).join('<br>')}${item.names.length > 5 ? '<br>…' : ''}</p></div>`).join('') : '<p>Nenhum apoiador ativo encontrado com os filtros atuais.</p>'; $('preview').srcdoc = `<!doctype html><html><head><base href="${location.href}"><link rel="stylesheet" href="../overlay/styles.css"></head><body><script>window.OVERLAY_DATA=${JSON.stringify({ ...payload, audioFile: null }).replace(/</g, '\\u003c')}</script><script src="../overlay/overlay.js"></script></body></html>`; }
function parseCsv(text) { text = text.replace(/^\uFEFF/, ''); const firstLine = text.split(/\r?\n/, 1)[0], delimiter = (firstLine.match(/;/g) || []).length > (firstLine.match(/,/g) || []).length ? ';' : ','; const cells = []; let field = '', row = [], quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i], next = text[i + 1]; if (char === '"' && quoted && next === '"') { field += '"'; i++; } else if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { row.push(field); field = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && next === '\n') i++; row.push(field); cells.push(row); row = []; field = ''; } else field += char; } if (field || row.length) { row.push(field); cells.push(row); } const headers = (cells.shift() || []).map(value => value.trim()); return { headers, rows: cells.filter(row => row.some(value => value.trim())).map(row => Object.fromEntries(headers.map((header, index) => [header, row[index] || '']))) }; }
function normalise(value) { return String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().replace(/\s+/g, ' ').toLowerCase(); }
function clampNumber(value, fallback) { return Math.min(3600, Math.max(1, Number(value) || fallback)); }
function basename(filePath) { return filePath.split(/[\\/]/).pop(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]); }
function setStatus(message) { $('status').textContent = message; }
